---
glob: '**/*.html{+*,}.erb'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  FinalNewline:
    enabled: true
  # Requires i18n translations for all string content. undocumented currently.
  # HardCodedString:
  #   enabled: true
  # PartialInstanceVariable:
  #   enabled: true
  # https://github.com/Shopify/erb-lint?tab=readme-ov-file#requirescriptnonce
  # RequireScriptNonce:
  #   enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/SpaceInsideHashLiteralBraces:
       Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
