# inspired by
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara
  # - rubocop-factory_bot

inherit_gem:
  # https://github.com/standardrb/standard#running-standards-rules-via-rubocop
  standard: config/ruby-3.3.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

# Strict rules to prevent todo overrides
Lint/Debugger: # don't leave binding.pry or debugger
  Enabled: true
  Exclude: []

Minitest/Focus: # run ALL tests on CI
  Enabled: true
  Exclude: []

Rails/Output: # Don't leave puts-debugging
  Enabled: true
  Exclude: []

Rails/FindEach: # each could severely affect the performance, use find_each
  Enabled: true
  Exclude: []

Rails/UniqBeforePluck: # uniq.pluck and not pluck.uniq
  Enabled: true
  Exclude: []

# Customizationization of rules
Minitest/MultipleAssertions:
  Exclude:
    # multiple assertions in capybara tests are okay (expensive/multi-step)
    - 'test/system/**/*'
Rails/DefaultScope:
  Enabled: true
